version: '3.1'

services:
  app:
    image: jamestechz/filesystem-api:v0.7
    ports:
    - 5000:5000
    environment:
    - ADMIN_USER=chris
    - ADMIN_PASSWD=api
    - SECRET=sky
    volumes:
    - type: bind
      source: /home/ec2-user/_files
      target: /app/_files
