version: '3.2'

services:
  app:
    image: jamestechz/filesystem-api:v1.1
    ports:
    - 5000:5000
    environment:
    - ADMIN_USER=chris
    - ADMIN_PASSWD=api
    - SECRET=sky
    volumes:
    - type: bind
      source: /home/ec2-user/_files
      # source: /home/tungvs/upwork/chris/filesystem-api/_files
      target: /app/_files
